homeassistant:
  name: Home
  latitude: MY_LATITUDE
  longitude: MY_LONGITUDE
  temperature_unit: C
  time_zone: Europe/Stockholm
  # Customization
  customize:
    sensor.netatmo_indoors_co2:
      friendly_name: CO2
    sensor.netatmo_indoors_humidity:
      friendly_name: Humidity
    sensor.netatmo_indoors_noise:
      friendly_name: Noise
    sensor.netatmo_indoors_pressure:
      friendly_name: Pressure
    sensor.netatmo_indoors_temperature:
      friendly_name: Temperature
    sensor.netatmo_indoors_max_temp:
      friendly_name: Temperature (max)
    sensor.netatmo_indoors_min_temp:
      friendly_name: Temperature (min)
    sensor.netatmo_kids_bedroom_co2:
      friendly_name: CO2
    sensor.netatmo_kids_bedroom_humidity:
      friendly_name: Humidity
    sensor.netatmo_kids_bedroom_temperature:
      friendly_name: Temperature
    sensor.netatmo_kids_bedroom_max_temp:
      friendly_name: Temperature (max)
    sensor.netatmo_kids_bedroom_min_temp:
      friendly_name: Temperature (min)
    sensor.netatmo_outdoors_humidity:
      friendly_name: Humidity
    sensor.netatmo_outdoors_temperature:
      friendly_name: Temperature
    sensor.netatmo_outdoors_max_temp:
      friendly_name: Temperature (max)
    sensor.netatmo_outdoors_min_temp:
      friendly_name: Temperature (min)
    switch.wemoone:
      friendly_name: World Globe
    switch.wemotwo:
      friendly_name: Reading light

http:
  api_password: PASSWORD_TO_WEB_INTERFACE

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

# ########################
# Groups, sensors, ...
# ########################

group:
  balcony:
    name: balcony
    entities:
      - sensor.netatmo_outdoors_humidity
      - sensor.netatmo_outdoors_temperature
      - sensor.netatmo_outdoors_max_temp
      - sensor.netatmo_outdoors_min_temp
  kids_bedroom:
    name: Kids Bedroom
    entities:
      - sensor.netatmo_kids_bedroom_co2
      - sensor.netatmo_kids_bedroom_humidity
      - sensor.netatmo_kids_bedroom_temperature
      - sensor.netatmo_kids_bedroom_max_temp
      - sensor.netatmo_kids_bedroom_min_temp
  kitchen:
    name: Kitchen
    entities:
      - media_player.kitchen
  living_room:
    name: Living Room
    entities:
      - media_player.living_room_1
      - media_player.living_room_5
      - sensor.netatmo_indoors_co2
      - sensor.netatmo_indoors_humidity
      - sensor.netatmo_indoors_noise
      - sensor.netatmo_indoors_pressure
      - sensor.netatmo_indoors_temperature
      - sensor.netatmo_indoors_max_temp
      - sensor.netatmo_indoors_min_temp
      - switch.wemoone
      - switch.wemotwo

wemo:

media_player:
  platform: sonos

netatmo:
  api_key: NETATMO_API_KEY
  secret_key: NETATMO_SECRET_KEY
  username: NETATMO_USERNAME
  password: NETATMO_PASSWORD

sensor:
  platform: netatmo
  modules:
    Indoors:
      - temperature
      - max_temp
      - min_temp
      - humidity
      - noise
      - pressure
      - co2
    Outdoors:
      - temperature
      - max_temp
      - min_temp
      - humidity
    Kids bedroom:
      - temperature
      - max_temp
      - min_temp
      - humidity
      - co2
